services:
  devenv:
    image: devenv
    container_name: devenv
    volumes:
      - ./zinit:/etc/zinit
      - ./tmuxp:/etc/tmuxp
      - ./scripts:/root/scripts
    environment: 
      NETWORK: "qa"
      MNEMONICS: "mom picnic deliver again rug night rabbit music motion hole lion where"
    entrypoint: [ "/sbin/zinit", "init" ]