services:
  tfgrid:
    image: tfgrid
    container_name: tfgrid
    volumes:
      - ./zinit:/etc/zinit
      - ./tmuxp:/etc/tmuxp
      - ./scripts:/root/scripts
    environment: 
      SUBSTRATE: "wss://tfchain.dev.grid.tf"
      MNEMONICS: "mom picnic deliver again rug night rabbit music motion hole lion where"
      # PEERS: "tcp:\\\/\\\/gent01.grid.tf:9943\\\n tcp:\\\/\\\/gent02.grid.tf:9943\\\n tcp:\\\/\\\/gent03.grid.tf:9943\\\n tcp:\\\/\\\/gent04.grid.tf:9943\\\n tcp:\\\/\\\/gent01.test.grid.tf:9943\\\n tcp:\\\/\\\/gent02.test.grid.tf:9943\\\n tcp:\\\/\\\/gent01.dev.grid.tf:9943\\\n tcp:\\\/\\\/gent02.dev.grid.tf:9943\\\n"
      # PUBLIC_KEY: "5011157c2451b238c99247b9f0793f66e5b77998272c00676d23767fe3d576d8" 
      # PRIVATE_KEY: "ff5b3012dbec23e86e2fde7dcd3c951781e87fe505be225488b50a6bb27662f75011157c2451b238c99247b9f0793f66e5b77998272c00676d23767fe3d576d8"

    # tun access
    cap_add:
      - NET_ADMIN
    network_mode: host  
    devices:
      - /dev/net/tun
      
    entrypoint: [ "/sbin/zinit", "init" ]