version: '3.9'
name: "tfgrid"

services:
  tfchain:
    build:
      context: .
      dockerfile: ubuntu.Dockerfile
    ports:
      - "30333:30333"
    restart: unless-stopped
    volumes:
      - ./tfchain/zinit/:/etc/zinit
      - ./tfchain/scripts:/scripts
      - ~/myhost/:/source
