services:
  devenv:
    image: 3bot
    container_name: devenv
    volumes:
      - ./zinit:/etc/zinit
      - ./tmuxp:/etc/tmuxp
      - ./scripts:/root/scripts
    environment: 
      NETWORK: "qa"
      MNEMONICS: ""
    entrypoint: [ "/sbin/zinit", "init" ]