name: Deploy static documentation to Pages

on:
  push:
    branches: ["development"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-documentation:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Vlang dependencies
        run: sudo apt update && sudo apt install -y libgc-dev

      - name: Setup Vlang
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate documentation
        run: |
            v doc -all -m . -o /tmp/vbuilders -f html -readme

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "/tmp/vbuilders/_docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
